# Generated by Django 5.2 on 2025-06-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emergencycontact_address_emergencycontact_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='shown_to_user',
            field=models.BooleanField(default=False),
        ),
    ]
